"""Representation of SEQ nodes for the Abstract Syntax Tree."""

from typing import Union

from typing_extensions import override

from src.ast_nodes.node import Node


class SEQ(Node):
    """
    Implement the representation of a sequence of statements for the AST.

    The node doesn't have any semantics itself, `instruction`, or has a
    certificate. Its only purpose is to help structuring the AST.
    """

    @override
    def __init__(self, **kwargs) -> None:
        super().__init__(uses_register=False)

        self.children: list[Node] = []

    def add_child(self, child: Node) -> None:
        """
        Add a child Node to the `self.children` list.

        Parameters
        ----------
        child : Node
            The child to be added to the list.
        """

        self.children.append(child)

    @override
    def get_certificate_label(self) -> list[str]:
        """
        Get the contents of `certificate_label`.

        For `SEQ` nodes, obtain the certificate from the `children` subtrees,
        recursively. The `SEQ` node itself does not have a certificate.

        Returns
        -------
        : list of str
            A list containing the certificate label of the `Node`.
        """

        certificate_label: list[str] = []

        for child in self.children:
            certificate_label.extend(child.get_certificate_label())

        return certificate_label

    @override
    def print(self, indent: int = 0) -> None:
        """
        Print the string representation of this `Conditional`.

        The node itself is aligned with `indent`, and its children are padded
        with an additional left space.

        Parameters
        ----------
        indent : int (optional, default = 0)
            The number of left padding spaces to indent.
        """

        super().print(indent)

        for child in self.children:
            child.print(indent + 1)

    @override
    def generate_code(
        self, register: int, environment: dict[str, dict[int, str]]
    ) -> tuple[
        list[dict[str, Union[int, str, float]]],
        int,
        dict[int, str]
    ]:
        """
        Generate the code associated with this `SEQ`.

        For this node specialization, return a list with the children's code,
        generated in the same order as they appear in the `children` attribute.
        The `SEQ` node itself does not generate code, for it has no associated
        `instruction`.

        Parameters
        ----------
        register : int
            The number of the register to be used by the code generated by this
            Node.
        environment : dict[int, str]
            The compiler's environment, that maps variables IDs to memory
            addresses and function IDs to instructions indices.

        Returns
        -------
        code : list of dict
            Return a list of dictionaries containing code metadata: the register
            to be used, the related `instruction` and its metadata.
        register : int
            The number of the next register available.
        environment : dict[int, str]
            The updated {var_id: address} environment mapping.
        """

        code: list[dict[str, Union[int, str, None]]] = []

        for child in self.children:
            child_code, register, environment = child.generate_code(
                register=register,
                environment=environment
            )
            code.extend(child_code)

        return code, register, environment

    @override
    def certificate(
        self,
        positional_prime: int,
        certificator_env: dict[int, list[int]]
    ) -> tuple[int, dict[int, list[int]]]:
        """
        Compute the certificate of the current `SEQ`, and set this attribute.

        For `SEQ` nodes, certificate the child nodes in the same order as they
        appear in the `children` list. The `SEQ` node itself is not certified.

        Parameters
        ----------
        positional_prime : int
            A prime number that denotes the relative position of this node in
            the source code.
        certificator_env : dict[int, list[int]]
            The certificators's environment, that maps variables IDs to
            encodings of their types.
        certificator_env : dict[int, list[int]]
            The updated certificator's environment, with any additional
            information about the variable's types it might have captured.

        Returns
        -------
        : int
            The prime that comes immediately after `positional_prime`.
        """

        for child in self.children:
            (
                positional_prime,
                certificator_env
            ) = child.certificate(positional_prime, certificator_env)

        return positional_prime, certificator_env
