"""Representation of IFELSE nodes for the Abstract Syntax Tree."""

from typing import Union

from typing_extensions import override

from src.ast_nodes.node import Node
from src.ast_nodes.conditionals.conditional import Conditional


class IFELSE(Conditional):
    """
    Implement the representation of a conditional for the AST.

    Parameters
    ----------
    id : int
        The ID of the Node.
    parenthesis_expression : Node
        The node representation of the expression to be evaluated.
    statement_if_true : Node
        The node representation of code to run if the `parenthesis_expression`
        evaluates to `True`.
    statement_if_false : Node
        The node representation of code to run if the `parenthesis_expression`
        evaluates to `False`.
    """

    @override
    def __init__(
        self,
        id: int,
        parenthesis_expression: Node,
        statement_if_true: Node,
        statement_if_false: Node,
    ) -> None:
        super().__init__(id, parenthesis_expression, statement_if_true)

        self.statement_if_false: Node = statement_if_false

    @override
    def get_certificate_label(self) -> list[str]:
        """
        Get the contents of `certificate_label`.

        For `IFELSE` nodes, first call the `Conditional.get_certificate_label`
        method, and compose it with the `certificate_label` obtained recursively
        from the `statement_if_false` subtree.

        Returns
        -------
        : list of str
            A list containing the certificate label of the `Node`.
        """

        return [
            *super().get_certificate_label(),
            *self.statement_if_false.get_certificate_label(),
        ]

    @override
    def print(self, indent: int = 0) -> None:
        """
        Print the string representation of this `Conditional`.

        The node itself is aligned with `indent`, and its children are padded
        with an additional left space.

        Parameters
        ----------
        indent : int (optional, default = 0)
            The number of left padding spaces to indent.
        """

        super().print(indent)

        self.statement_if_false.print(indent + 1)

    @override
    def generate_code(self, register: int) -> tuple[
        int,
        list[dict[str, Union[int, str]]]
    ]:
        """
        Generate the code associated with this `IFELSE`.

        For this node specialization, generate code from the
        `parenthesis_expression` first, add a conditional jump to the first
        instruction of the `statement_if_false` subtree -- i.e., to jump to if
        the `parenthesis_expression` evaluates to `False` --, then generate
        code from the `statement_if_true`, add an unconditional jump to the
        last instruction of teh `statement_if_false` subtree, and then finally
        generate code from `statement_if_false`.

        Parameters
        ----------
        register : int
            The number of the register to be used by the code generated by this
            Node.

        Returns
        -------
        register : int
            The number of the next register available.
        ifelse_code : list of dict
            Return a list of dictionaries containing code metadata: the related
            `instruction`, and node `id`, and `value`.
        """

        register, parenthesis_expression_code = self.parenthesis_expression.generate_code(
            register=register
        )

        register, statement_if_true_code = self.statement_if_true.generate_code(
            register=register
        )

        register, statement_if_false_code = self.statement_if_false.generate_code(
            register=register
        )

        # The jump target is the amount of instructions in the
        # `statement_if_true` block (add 2 to land right after the unconditional
        # jump added later on)
        instructions_to_jump_over_if = len(statement_if_true_code) + 2
        conditional_jump = {
            "instruction": "JZ",
            "metadata": {
                "jump_size": instructions_to_jump_over_if
            }
        }

        # The jump target is the amount of instructions in the
        # `statement_if_false` block (add 1 to land right after the last
        # instruction of the `statemente_if_false` block)
        instructions_to_jump_over_else = len(statement_if_false_code) + 1
        unconditional_jump = {
            "instruction": "JMP",
            "metadata": {
                "jump_size": instructions_to_jump_over_else
            }
        }

        # If `parenthesis_expression` evals to `False`, jump to the instruction
        # with ID `_beginning_of_else_block_id`. If not, execute the
        # `_statement_if_true_code`. However, add an unconditional jump right
        # after the `_statement_if_true_code` in order to skip the
        # `_statement_if_false_code`.
        ifelse_code: list[dict[str, Union[int, str]]] = [
            *parenthesis_expression_code,
            conditional_jump,
            *statement_if_true_code,
            unconditional_jump,
            *statement_if_false_code,
        ]

        return register, ifelse_code

    @override
    def certificate(self, prime: int) -> int:
        """
        Compute the certificate of the current `IFELSE`, and set this attribute.

        For `IFELSE` nodes, certificate the `parenthesis_expression`,
        recursively, and the `IFELSE` itself, and then the children
        `statement` nodes -- also recursively -- in order (i.e., the
        `statement_if_true` and then the `statement_if_false` subtrees).

        Parameters
        ----------
        prime : int
            A prime number that represents the relative position of the `Node`
            in the AST.

        Returns
        -------
        : int
            A prime number that comes after the given `prime`.
        """

        prime = super().certificate(prime)

        return self.statement_if_false.certificate(prime)
